version: "3"
services:
  # mongodb:
  #   image: "mongo:6.0.6"
  #   volumes:
  #     - data:/data/db
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    # depends_on:
    #   - mongodb
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  data:
  logs:
# Note : as all the books data are populated in localhost mongodb ,we are using localhost mongodb instead of container's mongodb.
# If container mongodb to be used then can uncomment
